[package]
name = "captcha"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519 = "1.3.0"
ed25519-dalek = "1.0.1"
sha2 = "0.10.0"